site_name: p1-kernel

theme:
  name: material

  # 404 page
  static_templates:
  - 404.html

  navigation_depth: 3

  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: deep purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search

nav:
  - exp0: lesson00/rpi-os.md
  - exp1: lesson01/rpi-os.md
  - exp2: lesson02/rpi-os.md
  - exp3: lesson03/rpi-os.md
  - exp4a: lesson04a/rpi-os.md
  - exp4b: lesson04b/rpi-os.md
  - exp5: lesson05/rpi-os.md
  - exp6: lesson06/rpi-os.md
  - /qemu: qemu.md
  - /gdb: gdb.md
  - /aarch64: aarch64-cheatsheet.md
  - /inspect-kernel-binary: inspect-kernel-binary.md
